# Setup
title:            Jay Shoemaker
tagline:          'Entrepreneur & Product Manager.'
description:      'Entrepreneur & Product Manager.'
url:              https://jayshoemaker.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Jay Shoemaker'
  url:            https://twitter.com/JayShoe

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  

# Custom vars
version:          3.0.0
