# Setup
title:            Jay P Shoemaker IV
tagline:          'Entrepreneur & Product Manager'
description:      'Entrepreneur & Product Manager'
url:              https://jayshoemaker.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Jay P Shoemaker IV'
  url:            https://twitter.com/JayShoe

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  

# Custom vars
version:          3.0.0
